const WPP_LINEAR='5516997746888';
const EMPRESA={nome:'LINEAR MOVEIS PLANEJADOS LTDA',cnpj:'25.967.859/0001-03',endereco:'AVENIDA ALBERTO SANTOS DUMONT, 209, JARDIM DUMONT, ARARAQUARA, SP, 14807-219',telefone:'(16) 99774-6888'};
const K={prod:'linear_cloud_produtos',itens:'linear_cloud_itens',orcs:'linear_cloud_orcamentos',cfg:'linear_cloud_cfg'};
function uid(){return 'id'+Math.random().toString(36).slice(2,9)+Date.now().toString(36)}
function money(v){return (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function get(k,def){try{return JSON.parse(localStorage.getItem(k)||'null')??def}catch{return def}}
function set(k,v){localStorage.setItem(k,JSON.stringify(v));scheduleAutoSync()}
let produtos=get(K.prod,null)||[
{id:uid(),nome:'Cozinha planejada sob medida',categoria:'Cozinha',un:'m linear',preco:2850,desc:'Móveis planejados para cozinha com materiais, mão de obra e frete inclusos.'},{id:uid(),nome:'Armário aéreo cozinha',categoria:'Cozinha',un:'m linear',preco:1450,desc:'Armário aéreo em MDF com acabamento conforme projeto.'},{id:uid(),nome:'Balcão inferior cozinha',categoria:'Cozinha',un:'m linear',preco:1700,desc:'Balcão inferior com portas/gavetas conforme necessidade do cliente.'},{id:uid(),nome:'Guarda-roupa planejado',categoria:'Quarto',un:'m linear',preco:2300,desc:'Guarda-roupa sob medida com divisórias internas personalizadas.'},{id:uid(),nome:'Cabeceira planejada',categoria:'Quarto',un:'un',preco:1800,desc:'Cabeceira sob medida com painel, iluminação ou criados conforme projeto.'},{id:uid(),nome:'Painel de TV planejado',categoria:'Sala',un:'un',preco:2500,desc:'Painel decorativo sob medida para sala ou quarto.'},{id:uid(),nome:'Rack planejado',categoria:'Sala',un:'un',preco:2200,desc:'Rack sob medida com acabamento premium.'},{id:uid(),nome:'Cristaleira planejada',categoria:'Sala',un:'un',preco:3600,desc:'Cristaleira com portas, iluminação e acabamento conforme projeto.'},{id:uid(),nome:'Banheiro planejado',categoria:'Banheiro',un:'un',preco:2800,desc:'Gabinete e complementos planejados para banheiro.'},{id:uid(),nome:'Escritório planejado',categoria:'Escritório',un:'m linear',preco:1900,desc:'Bancada, armários e módulos para home office.'},{id:uid(),nome:'Lavanderia planejada',categoria:'Lavanderia',un:'m linear',preco:1850,desc:'Armários e bancada para lavanderia sob medida.'},{id:uid(),nome:'Divisor de ambiente muxarabi',categoria:'Decorativo',un:'m²',preco:950,desc:'Divisor de ambientes decorativo com acabamento personalizado.'},{id:uid(),nome:'Porta oculta / porta mimetizada',categoria:'Decorativo',un:'un',preco:3200,desc:'Solução de porta integrada ao painel/divisor.'},{id:uid(),nome:'Iluminação LED embutida',categoria:'Extra',un:'un',preco:450,desc:'Ponto de iluminação LED aplicado ao móvel.'},{id:uid(),nome:'Ferragem premium',categoria:'Extra',un:'kit',preco:850,desc:'Upgrade de ferragens premium conforme projeto.'}
];
let itens=get(K.itens,[]); if(!itens.length)itens=[{produtoId:produtos[0].id,qtd:1,obs:''}];
function produto(id){return produtos.find(p=>p.id===id)||produtos[0]}
function saveProdutos(){set(K.prod,produtos)} function saveItens(){set(K.itens,itens)}
function calc(){const sub=itens.reduce((s,it)=>s+(+it.qtd||0)*(produto(it.produtoId).preco||0),0),dp=+document.getElementById('desconto').value||0,desc=sub*dp/100,total=sub-desc;subtotal.textContent=money(sub);descontoValor.textContent=money(desc);document.getElementById('total').textContent=money(total);return{sub,desc,total}}
function renderItens(){const box=itensEl();box.innerHTML='';itens.forEach((it,i)=>{const p=produto(it.produtoId),row=document.createElement('div');row.className='item-row';row.innerHTML=`<label>Produto ligado<select data-i="${i}" data-k="produtoId">${produtos.map(pr=>`<option value="${pr.id}" ${pr.id===it.produtoId?'selected':''}>${pr.nome}</option>`).join('')}</select></label><label>Descrição<input value="${p.desc||''}" disabled></label><label>Qtd<input type="number" min="0" step="0.01" value="${it.qtd||1}" data-i="${i}" data-k="qtd"></label><label>Un<input value="${p.un||'un'}" disabled></label><button class="danger small" onclick="remItem(${i})">Excluir</button><label style="grid-column:1/-1">Observação<input value="${it.obs||''}" data-i="${i}" data-k="obs" placeholder="medidas, cor, acabamento..."></label>`;box.appendChild(row)});box.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',e=>{const i=e.target.dataset.i,k=e.target.dataset.k;itens[i][k]=k==='qtd'?+e.target.value:e.target.value;saveItens(); if(k==='produtoId')renderItens(); calc()}))}
function itensEl(){return document.getElementById('itens')} function remItem(i){itens.splice(i,1);if(!itens.length)itens.push({produtoId:produtos[0].id,qtd:1,obs:''});saveItens();renderItens();calc()}
btnAddItem.onclick=()=>{itens.push({produtoId:produtos[0].id,qtd:1,obs:''});saveItens();renderItens();calc()}; ['desconto','entrada','parcelas','validade','cliente','telefone','cidade','ambiente'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{calc();scheduleAutoSync()}));
function renderProdutos(){const box=produtosLista;box.innerHTML='';produtos.forEach((p,i)=>{const row=document.createElement('div');row.className='produto-row';row.innerHTML=`<label>Nome<input value="${p.nome}" data-i="${i}" data-k="nome"></label><label>Categoria<input value="${p.categoria}" data-i="${i}" data-k="categoria"></label><label>Un<input value="${p.un}" data-i="${i}" data-k="un"></label><label>Preço interno<input type="number" value="${p.preco}" data-i="${i}" data-k="preco"></label><button class="secondary small" data-save="${i}">Salvar</button><button class="danger small" data-del="${i}">Excluir</button><label style="grid-column:1/-1">Descrição<input value="${p.desc||''}" data-i="${i}" data-k="desc"></label>`;box.appendChild(row)});box.querySelectorAll('input').forEach(el=>el.addEventListener('input',e=>{const i=e.target.dataset.i,k=e.target.dataset.k;produtos[i][k]=k==='preco'?+e.target.value:e.target.value}));box.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{saveProdutos();renderItens();calc();log('Produto salvo e sincronização automática acionada.')});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{produtos.splice(+b.dataset.del,1);saveProdutos();renderProdutos();renderItens();calc()})}
btnNovoProduto.onclick=()=>{produtos.unshift({id:uid(),nome:'Novo produto',categoria:'Categoria',un:'un',preco:0,desc:'Descrição do produto/serviço.'});saveProdutos();renderProdutos()}
function dados(){return {cliente:cliente.value,telefone:telefone.value,cidade:cidade.value,ambiente:ambiente.value,desconto:desconto.value,entrada:entrada.value,parcelas:parcelas.value,validade:validade.value,...calc()}}
btnSalvar.onclick=()=>{let arr=get(K.orcs,[]);arr.unshift({id:uid(),data:new Date().toLocaleString('pt-BR'),updatedAt:Date.now(),dados:dados(),itens:structuredClone(itens)});set(K.orcs,arr);renderSalvos();alert('Orçamento salvo com sucesso.')}
function renderSalvos(){const arr=get(K.orcs,[]);orcamentosSalvos.innerHTML=arr.length?'':'<p>Nenhum orçamento salvo ainda.</p>';arr.forEach((o,i)=>{const d=document.createElement('div');d.className='saved-row';d.innerHTML=`<strong>${o.dados.cliente||'Sem cliente'}</strong><span>${o.data}</span><span>${money(o.dados.total)}</span><button class="secondary small" onclick="carregarSalvo(${i})">Carregar</button>`;orcamentosSalvos.appendChild(d)})}
function carregarSalvo(i){const o=get(K.orcs,[])[i];['cliente','telefone','cidade','ambiente','validade','desconto','entrada','parcelas'].forEach(k=>{if(document.getElementById(k))document.getElementById(k).value=o.dados[k]||''});itens=o.itens;saveItens();renderItens();calc();document.querySelector('[data-view="orcamento"]').click()}
function mensagemWhats(){const d=dados(),entrada=d.total*(+d.entrada||30)/100,saldo=d.total-entrada;return encodeURIComponent(`Olá, segue orçamento gerado pelo sistema da Linear.\n\nCliente: ${d.cliente||'-'}\nAmbiente: ${d.ambiente||'-'}\nTotal: ${money(d.total)}\nEntrada sugerida: ${money(entrada)}\nSaldo: ${money(saldo)}\n\nO PDF foi gerado pelo sistema.\n\n${EMPRESA.nome}\n${EMPRESA.telefone}`)}
function gerarPdf(){const d=dados(),entrada=d.total*(+d.entrada||30)/100,parcela=(d.total-entrada)/(+d.parcelas||1);printArea.innerHTML=`<div class="pdf-page"><div class="pdf-header"><div><div class="pdf-title">Proposta Comercial</div><strong>Orçamento de Móveis Planejados</strong></div><div class="pdf-company"><strong>${EMPRESA.nome}</strong><br>CNPJ: ${EMPRESA.cnpj}<br>${EMPRESA.endereco}<br>${EMPRESA.telefone}</div></div><div class="pdf-section"><h3>Dados do cliente</h3><p><strong>Cliente:</strong> ${d.cliente||'-'}<br><strong>Telefone:</strong> ${d.telefone||'-'}<br><strong>Cidade:</strong> ${d.cidade||'-'}<br><strong>Ambiente:</strong> ${d.ambiente||'-'}<br><strong>Data:</strong> ${new Date().toLocaleDateString('pt-BR')}</p></div><div class="pdf-section"><h3>Relatório inicial</h3><p>Para a nossa empresa, é um prazer apresentar essa proposta após as conversas que tivemos sobre o que é importante para alcançarmos o bem-estar e a qualidade de vida no seu dia a dia através dos nossos móveis planejados.</p><p>Esse orçamento foi pensado para ser o melhor investimento para você, mantendo móveis duráveis que vão trazer sofisticação, funcionalidade e valorização aos seus ambientes.</p></div><div class="pdf-section"><h3>Itens do orçamento</h3><table><thead><tr><th>Item</th><th>Descrição</th><th>Qtd.</th><th>Un.</th><th>Total</th></tr></thead><tbody>${itens.map((it,i)=>{const p=produto(it.produtoId);return `<tr><td>${i+1}. ${p.nome}</td><td>${p.desc}${it.obs?'<br><em>Obs.: '+it.obs+'</em>':''}</td><td>${it.qtd}</td><td>${p.un}</td><td>${money((it.qtd||0)*(p.preco||0))}</td></tr>`}).join('')}</tbody></table></div><div class="pdf-section pdf-total">Total da proposta: ${money(d.total)}</div><div class="pdf-section"><h3>Condições comerciais</h3><p><strong>Entrada de ${d.entrada}%:</strong> ${money(entrada)}<br><strong>Saldo em ${d.parcelas} parcela(s):</strong> ${money(parcela)} cada<br><strong>Validade:</strong> ${d.validade||'7 dias'}</p></div><div class="pdf-section terms"><h3>Condições de contrato</h3><ol><li>Nesse orçamento já estão considerados os valores de mão de obra, materiais e frete.</li><li>A validade deste orçamento é de 7 dias após a emissão do mesmo. Após esse período será necessário atualizar valores devido à variação de preços de insumos.</li><li>Para iniciarmos o trabalho é necessário o pagamento de sinal de 30% do valor total.</li><li>Em caso de desistência, após o início da produção, o valor do sinal poderá não ser restituído.</li><li>Os móveis têm garantia de 1 ano. A garantia perde a validade por mau uso como batidas, riscos e excesso de peso.</li><li>O prazo de entrega é de até 14 dias úteis após aprovação do orçamento e pagamento do sinal.</li></ol></div><div class="pdf-section signature-grid"><p>_________________________________________<br>Assinatura do cliente</p><p>_________________________________________<br>Assinatura da empresa<br><strong>${EMPRESA.nome}</strong></p></div></div>`;window.print()}
btnPdf.onclick=gerarPdf; btnWhatsapp.onclick=()=>{gerarPdf();setTimeout(()=>window.open(`https://wa.me/${WPP_LINEAR}?text=${mensagemWhats()}`,'_blank'),600)};
function pacote(){return {version:6,updatedAt:Date.now(),produtos,itens,orcamentos:get(K.orcs,[])}}
function aplicar(data){if(data.produtos)produtos=data.produtos;if(data.itens)itens=data.itens;set(K.prod,produtos);set(K.itens,itens);if(data.orcamentos)set(K.orcs,data.orcamentos);renderProdutos();renderItens();renderSalvos();calc()}
let cfg=get(K.cfg,{token:'',gistId:''}), syncTimer=null;function log(t){cloudLog.textContent=new Date().toLocaleTimeString('pt-BR')+' - '+t+'\n'+cloudLog.textContent}function cloudUI(){ghToken.value=cfg.token||'';ghGist.value=cfg.gistId||'';cloudBadge.textContent=cfg.gistId?'GitHub ativo':'Local';cloudSmall.textContent=cfg.gistId?'Backup automático ligado.':'Configure o GitHub Gist.'}function headers(){return {'Authorization':'token '+cfg.token,'Accept':'application/vnd.github+json','Content-Type':'application/json'}}
btnSaveCloud.onclick=()=>{cfg={token:ghToken.value.trim(),gistId:ghGist.value.trim()};localStorage.setItem(K.cfg,JSON.stringify(cfg));cloudUI();log('Configuração salva.')};
async function createGist(){if(!cfg.token)throw Error('Token GitHub não informado.');let r=await fetch('https://api.github.com/gists',{method:'POST',headers:headers(),body:JSON.stringify({description:'Backup Linear Orçamentos Cloud',public:false,files:{'linear-orcamentos-backup.json':{content:JSON.stringify(pacote(),null,2)}}})});if(!r.ok)throw Error(await r.text());let j=await r.json();cfg.gistId=j.id;localStorage.setItem(K.cfg,JSON.stringify(cfg));cloudUI();log('Gist criado: '+cfg.gistId)}
async function pushCloud(){if(!cfg.token||!cfg.gistId)throw Error('Configure token e Gist ID.');let r=await fetch('https://api.github.com/gists/'+cfg.gistId,{method:'PATCH',headers:headers(),body:JSON.stringify({files:{'linear-orcamentos-backup.json':{content:JSON.stringify(pacote(),null,2)}}})});if(!r.ok)throw Error(await r.text());log('Backup enviado para GitHub.')}
async function pullCloud(){if(!cfg.token||!cfg.gistId)throw Error('Configure token e Gist ID.');let r=await fetch('https://api.github.com/gists/'+cfg.gistId,{headers:headers()});if(!r.ok)throw Error(await r.text());let j=await r.json(),file=j.files['linear-orcamentos-backup.json'];if(!file)throw Error('Arquivo de backup não encontrado no Gist.');aplicar(JSON.parse(file.content));log('Dados baixados da nuvem e aplicados neste dispositivo.')}
function scheduleAutoSync(){clearTimeout(syncTimer);if(cfg&&cfg.token&&cfg.gistId)syncTimer=setTimeout(()=>pushCloud().catch(e=>log('Falha no backup automático: '+e.message)),1500)}
btnCreateGist.onclick=()=>createGist().catch(e=>log('Erro: '+e.message));btnPushCloud.onclick=()=>pushCloud().catch(e=>log('Erro: '+e.message));btnPullCloud.onclick=()=>pullCloud().catch(e=>log('Erro: '+e.message));btnSyncNow.onclick=()=>pullCloud().then(pushCloud).catch(e=>log('Erro: '+e.message));
document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-btn,.view').forEach(e=>e.classList.remove('active'));btn.classList.add('active');document.getElementById('view-'+btn.dataset.view).classList.add('active');renderSalvos();cloudUI()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});saveProdutos();saveItens();renderProdutos();renderItens();renderSalvos();calc();cloudUI();
